// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: MarkFeedFetchedById.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const markFeedFetchedById = `-- name: MarkFeedFetchedById :one
update feeds
set updated_at = $2,
last_fetched_at = $2
where id = $1
RETURNING id, created_at, updated_at, name, url, user_id, last_fetched_at
`

type MarkFeedFetchedByIdParams struct {
	ID        uuid.UUID
	UpdatedAt sql.NullTime
}

func (q *Queries) MarkFeedFetchedById(ctx context.Context, arg MarkFeedFetchedByIdParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, markFeedFetchedById, arg.ID, arg.UpdatedAt)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}
